### ISSUE TITLE
Page demo not working with ios 15.2.1

### ISSUE THREAD

**Issue by tiendd2608** [wojtekmaj/react-pdf#1374]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

Page demo not working with ios 15.2
https://projects.wojtekmaj.pl/react-pdf/

![MicrosoftTeams-image](https://user-images.githubusercontent.com/36448779/223943978-ae2d6907-d6a2-4762-8e1a-dc438fa47c95.png)

Detail:
[Error] TypeError: key.split("+").at is not a function. (In 'key.split("+").at(-1)', 'key.split("+").at' is undefined)
    KeyboardManager

### Steps to reproduce

Go to page https://projects.wojtekmaj.pl/react-pdf/

### Expected behavior

Load pdf

### Actual behavior

Load fail pdf

### Environment

- **Browser (if applicable)**: Safari
- **React-PDF version**: 6.2.2
- **IOS**: 15.2.1

**Comment by rubenofen** [comment]
Same issue here, but not in the page demo in my production application:
https://app.innocard.me/en/card/bfee8a57-be22-42b5-b922-bad7be24fbdf

Please could you give me a workaround? Thank you.

**Comment by tiendd2608** [comment]
@rubenofen If you get the above error, you can use legacy version react-pdf@5.5.0

**Comment by heningyuan6256** [comment]
i find this problom too

**Comment by liuchunda** [comment]
No solution was found. Why did the problem turn off

**Comment by wojtekmaj** [comment]
Because it was a year ago. Most recent version of React-PDF requires iOS Safari 17.4 as documented.
